---
all:
  hosts:
    cdFMC:
      ansible_host: cisco-edmcnich.app.us.cdo.cisco.com
      ansible_network_os: cisco.fmcansible.fmc
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: True
      web_lb_public_ip: 23.100.31.160
